services:
  elasticsearch:
    image: elasticsearch:7.9.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "9200:9200"
    networks:
      - elk-network

  kibana:
    image: kibana:7.9.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-network

  dotnet-app:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: dotnet-app
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      - elasticsearch
    networks:
      - elk-network
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app/src  

networks:
  elk-network:
    driver: bridge
